root: true
env:
  browser: true
  es6: true
extends:
  - plugin:import/recommended
  - plugin:jsx-a11y/recommended
parserOptions:
  ecmaVersion: 7
  sourceType: module
plugins:
  - eslint-plugin-react
  - eslint-plugin-react-hooks
ignorePatterns:
  - '/build/**'
  - '/coverage/**'
  - '/dist/**'
  - '/examples/**'
  - '**/esm/**'
  - '**/cjs/**'
  - '**/types/**'
overrides:
  - files:
      - '**.{js,mjs}'
    extends:
      - airbnb
      - prettier
    rules:
      no-console:
        - off
  - files:
      - '**.{ts,tsx}'
    extends:
      - plugin:import/typescript
      - airbnb-typescript
      - prettier
    parser: '@typescript-eslint/parser'
    parserOptions:
      ecmaVersion: 7
      sourceType: module
      project: tsconfig.eslint.json
    plugins:
      - '@typescript-eslint/eslint-plugin'
    rules:
      no-param-reassign:
        - error
        - props: false
      no-underscore-dangle:
        - off
      react/require-default-props:
        - off
      '@typescript-eslint/naming-convention':
        - error
        - selector:
            - function
          format:
            - camelCase
            - PascalCase
          leadingUnderscore: allow
